const LANGUAGE_PROFILES = {
	de: null,
	en: {
		openVowels: ['a', 'e', 'o'],
		closeVowels: ['i', 'u', 'y'],
		semiVowels: ['j', 'w'],
		liquidConsonants: ['l', 'r'],
		nasalConsonants: ['m', 'n', 'ng'],
		fricativeConsonants: ['f', 'v', 's', 'z', 'h', 'th', 'sh'],
		affricateConsonants: ['ch', 'j'], // graphemisch später ggf. "ch","j"
		plosiveConsonants: ['p', 'b', 't', 'd', 'k', 'g'],
		allowedOnsets: [
			'b',
			'bl',
			'br',
			'c',
			'cl',
			'cr',
			'd',
			'dr',
			'f',
			'fl',
			'fr',
			'g',
			'gl',
			'gr',
			'h',
			'k',
			'kl',
			'kr',
			'l',
			'm',
			'n',
			'p',
			'pl',
			'pr',
			'r',
			's',
			'sh',
			'sk',
			'sl',
			'sm',
			'sn',
			'sp',
			'st',
			'str',
			't',
			'tr',
			'w',
		],
		allowedCodas: ['b', 'd', 'f', 'g', 'k', 'l', 'm', 'n', 'ng', 'p', 'r', 's', 'sh', 't'],
	},
};
